'use client'
import {useEffect,useRef,useState} from 'react'

type Mode='find'|'activate'|'pin'|'manage'
type Card={id:string;business_name:string;review_url:string;active:boolean;created_at:string;activated_at:string|null}
const clean=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)
const getHash=async(pin:string)=>{const b=new TextEncoder().encode(pin);const h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}

export default function Manage(){
 const [mode,setMode]=useState<Mode>('find');const [code,setCode]=useState('');const [card,setCard]=useState<Card|null>(null);const [name,setName]=useState('');const [review,setReview]=useState('');const [pin,setPin]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const refs=useRef<(HTMLInputElement|null)[]>([])
 const lookup=async()=>{if(code.length!==6)return;setBusy(true);setMsg('');const r=await fetch('/api/card?code='+code);const d=await r.json();setBusy(false);if(d.card){setCard(d.card);setMode('pin')}else{setMode('activate')}}
 const save=async()=>{if(!name.trim()||!review.trim()||pin.length!==4)return;setBusy(true);setMsg('');const pinHash=await getHash(pin);const r=await fetch('/api/card',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,name:name.trim(),review,pinHash,pin})});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||'Gagal menyimpan');return}setCard(d.card);setMode('manage');setPin('');setMsg('Kartu berhasil diaktifkan.')}}
 const unlock=async()=>{if(pin.length!==4||!card)return;setBusy(true);const pinHash=await getHash(pin);const stored=(await (await fetch('/api/card?code='+code+'&meta=1')).json()).pinHash;setBusy(false);if(pinHash!==stored){setMsg('PIN salah.');return}setName(card.business_name);setReview(card.review_url);setMode('manage');setPin('');setMsg('')}}
 const update=async(active=card?.active)=>{if(!card)return;setBusy(true);const pinHash=(await (await fetch('/api/card?code='+code+'&meta=1')).json()).pinHash;const r=await fetch('/api/card',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({code,name:name.trim(),review,pinHash,active})});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||'Gagal memperbarui');return}setCard(d.card);setMsg('Perubahan tersimpan.')}}
 const reset=async()=>{if(!card||!confirm('Reset kartu? Semua data akan dihapus dan kode bisa diaktivasi ulang.'))return;setBusy(true);await fetch('/api/card?code='+code,{method:'DELETE'});setBusy(false);setCard(null);setName('');setReview('');setPin('');setMode('find');setMsg('Kartu di-reset. Kode siap dipakai lagi.')}}
 const change=(i:number,v:string)=>{const x=v.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(-1);const a=code.split('');a[i]=x;setCode(a.join(''));if(x&&i<5)refs.current[i+1]?.focus()}
 return <main className="page"><div className="shell"><div className="top"><div className="brand">Review Card</div><div className="small">Kelola kartu</div></div>
 {mode==='find'&&<section className="card center"><div className="eyebrow">Kartu digital</div><h1 className="h1">Cari Kartu</h1><p className="sub">Masukkan kode 6 karakter pada kartu untuk mulai aktivasi atau mengelola kartu.</p><div className="otp">{Array.from({length:6}).map((_,i)=><input key={i} ref={e=>{refs.current[i]=e}} value={code[i]||''} onChange={e=>change(i,e.target.value)} onKeyDown={e=>{if(e.key==='Backspace'&&!code[i]&&i>0)refs.current[i-1]?.focus()}} maxLength={1} autoFocus={i===0}/>)}</div><button className="btn" disabled={code.length!==6||busy} onClick={lookup}>{busy?'Mengecek…':'Lanjutkan'}</button>{msg&&<div className="notice error">{msg}</div>}</section>}
 {mode==='activate'&&<section className="card"><div className="grid"><div><div className="eyebrow">Kode baru · {code}</div><h1 className="h1">Aktivasi Kartu</h1><p className="sub">Isi data usaha. Tampilan kartu di kanan akan berubah secara live saat mengetik.</p><label className="label">Nama Usaha</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Kedai Kopi Senja"/><label className="label">Link Google Review</label><input className="input" value={review} onChange={e=>setReview(e.target.value)} placeholder="https://g.page/r/..."/><label className="label">PIN 4 digit</label><input className="input" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" placeholder="••••"/><button className="btn" style={{marginTop:22}} disabled={!name.trim()||!review.trim()||pin.length!==4||busy} onClick={save}>{busy?'Menyimpan…':'Aktifkan Kartu'}</button>{msg&&<div className="notice error">{msg}</div>}</div><div className="preview"><div><div className="small" style={{color:'#cbd5e1'}}>REVIEW CARD · {code}</div><div className="name" style={{marginTop:20}}>{name||'Nama Usaha'}</div></div><div className="row"><img className="qrimg" src={'https://quickchart.io/qr?text='+encodeURIComponent((typeof window !== 'undefined' ? window.location.origin : '')+'/r/'+code)+'&size=180'} alt="QR kartu"/><div style={{fontSize:13,color:'#cbd5e1'}}>Scan untuk memberikan<br/>ulasan di Google</div></div></div></div></section>}
 {mode==='pin'&&<section className="card center"><div className="eyebrow">Kartu terdaftar</div><h1 className="h1">Masukkan PIN</h1><p className="sub">Kode <b>{code}</b> sudah terdaftar. Masukkan PIN 4 digit untuk masuk ke mode kelola.</p><div className="pinwrap"><input className="input" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" type="password" maxLength={4} autoFocus/><button className="btn" style={{marginTop:12}} disabled={pin.length!==4||busy} onClick={unlock}>Buka Kelola</button></div>{msg&&<div className="notice error">{msg}</div>}</section>}
 {mode==='manage'&&card&&<section className="card"><div className="grid"><div><div className="eyebrow">Kelola Kartu · {code}</div><h1 className="h1">Pengaturan Kartu</h1><p className="sub">Data tersimpan berdasarkan kode kartu dan tetap dapat diakses dari sesi/perangkat lain.</p><div className="row" style={{justifyContent:'space-between',padding:'14px 0',borderTop:'1px solid #eee',borderBottom:'1px solid #eee'}}><div><b>{card.active?'Aktif':'Nonaktif'}</b><div className="small">{card.active?'Fitur ulasan sedang menyala':'Fitur ulasan dimatikan tanpa menghapus data'}</div></div><button className={'toggle '+(card.active?'on':'')} onClick={()=>update(!card.active)} aria-label="Toggle aktif"/></div><label className="label">Nama Usaha</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/><label className="label">Link Google Review</label><input className="input" value={review} onChange={e=>setReview(e.target.value)}/><div className="actions"><button className="btn secondary" disabled={busy} onClick={()=>update(card.active)}>Simpan Perubahan</button><button className="btn danger" disabled={busy} onClick={reset}>Reset Kartu</button></div>{msg&&<div className="notice success">{msg}</div>}</div><div className="preview"><div><div className="small" style={{color:'#cbd5e1'}}>KARTU {card.active?'AKTIF':'NONAKTIF'}</div><div className="name" style={{marginTop:20}}>{name||card.business_name}</div></div><div className="row"><img className="qrimg" src={'https://quickchart.io/qr?text='+encodeURIComponent((typeof window !== 'undefined' ? window.location.origin : '')+'/r/'+code)+'&size=180'} alt="QR kartu"/><div style={{fontSize:13,color:'#cbd5e1'}}>Google Review<br/>{review||'Belum diatur'}</div></div></div></div></section>}
 </div></main>
}
